runtime: nodejs20
env: standard

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Configure sua DATABASE_URL do Neon aqui
  # DATABASE_URL: "postgresql://username:password@ep-xxx.us-east-1.aws.neon.tech/dbname?sslmode=require"
  SESSION_SECRET: "sua_chave_secreta_muito_segura_aqui_2024"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.8

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10