runtime: nodejs20
env: standard

env_variables:
  DATABASE_URL: "postgresql://postgres:nvs123@/vendas?host=/cloudsql/applicencas:us-central1:banco-vendas"
  NODE_ENV: "production"
  SESSION_SECRET: "nvs123"

beta_settings:
  cloud_sql_instances: "sistema-vendas-app:us-central1-c:banco-vendas"